# Create 3x3x3 matrix

In [3]:
import numpy as np
n=np.random.random((3,3,3))
print(n)

[[[0.55390328 0.02846351 0.95750351]
  [0.7300008  0.73096107 0.20125526]
  [0.12325788 0.47618974 0.5971633 ]]

 [[0.26092124 0.37383263 0.19469867]
  [0.97552481 0.12244992 0.5650712 ]
  [0.46236988 0.92799347 0.63440315]]

 [[0.31038114 0.14454985 0.0240563 ]
  [0.59133544 0.43041324 0.39500214]
  [0.59632393 0.77392658 0.1717637 ]]]


# Create 5x5 matrix with values 1,2,3,4

In [4]:
import numpy as np
x=np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Create 8x8 matrix and fill it with checkboard pattern

In [25]:
import numpy as np
x=np.ones((3,3))
print("Checkboard pattern:")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

Checkboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize 5x5 random matrix

In [7]:
x=np.random.random((3,3))
print("Original Array:")
print(x)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("After normalization:")
print(x)

Original Array:
[[0.61033996 0.62871353 0.59285759]
 [0.22754198 0.95884028 0.98884966]
 [0.25507415 0.4567602  0.41239935]]
After normalization:
[[0.50281639 0.52695062 0.47985279]
 [0.         0.9605818  1.        ]
 [0.03616431 0.30108487 0.24281559]]


# Common values between 2 arrays

In [26]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1:",array1)
array2 = [10, 30, 40]
print("Array2:",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]


# To get dates of yesterday,today and tomorrow

In [27]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# Consider 2 random arrays a and b and check if they are equal

In [12]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 1 1 1 0]
Second array:
[1 1 0 0 1 1]
Test above two arrays are equal or not!
False


# Create random vector of size 10 and replace the maximum value by 0

In [13]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.87138782 0.05550275 0.63510442 0.73600638 0.3922247  0.29205391
 0.24197437 0.67886712 0.60934888 0.35970312]
Maximum value replaced by -1:
[-1.          0.05550275  0.63510442  0.73600638  0.3922247   0.29205391
  0.24197437  0.67886712  0.60934888  0.35970312]


# To print all the values of an array

In [14]:
import numpy as np
n=np.array([1,2,3,4,5])
print("Values of an array:",n)

Values of an array: [1 2 3 4 5]


# Subtract the mean of each row of matrix

In [15]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.42059102 0.4904609  0.05593487 0.85154169 0.14566558 0.75596614
  0.08573982 0.9329945  0.84030074 0.28244157]
 [0.56692711 0.5446832  0.8616079  0.13979864 0.75850193 0.70586521
  0.53529521 0.6607689  0.41424035 0.64118279]
 [0.55750706 0.33454269 0.8402582  0.49366656 0.93284388 0.54361247
  0.1522395  0.42561215 0.54135108 0.42277097]
 [0.16004613 0.61061544 0.91746622 0.43130837 0.54028615 0.08259924
  0.07268563 0.80321048 0.99130999 0.42523385]
 [0.11528283 0.97339798 0.78046831 0.6008679  0.8936627  0.532544
  0.36948589 0.54090922 0.48756013 0.54082285]]

Subtract the mean of each row of the said matrix:

[[-0.06557266  0.00429722 -0.43022882  0.365378   -0.34049811  0.26980246
  -0.40042386  0.44683082  0.35413705 -0.20372211]
 [-0.01596002 -0.03820392  0.27872078 -0.44308848  0.17561481  0.12297809
  -0.04759191  0.07788178 -0.16864678  0.05829567]
 [ 0.03306661 -0.18989777  0.31581774 -0.03077389  0.40840342  0.01917202
  -0.37220095 -0.09882831  0.016

# How to add 1 to each element indexed by second vector

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
newarr = arr.reshape(4, 3)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# To get the diagonal of a dot product

In [19]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

# To find the most frequent value in an array

In [20]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[5 9 6 8 0 2 1 3 6 2 7 1 3 0 2 3 2 7 5 7 0 7 1 1 5 0 5 2 9 8 3 9 2 7 4 6 8
 1 3 5]
Most frequent value in the above array:
2


# To get the n largest values of an array

In [24]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# To create a record array from a regular array

In [22]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
